# Generated by Django 3.0.3 on 2021-01-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210103_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Profile_pic',
            field=models.ImageField(default='default.gif', upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Profile_pic',
            field=models.ImageField(default='default2.jpg', upload_to='profile_pic'),
        ),
    ]
