# Generated by Django 3.0.3 on 2021-01-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210103_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='teacher', max_length=300, null=True),
        ),
    ]
