# Generated by Django 3.0.3 on 2021-01-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210103_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default=1, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default=0, max_length=300, null=True),
        ),
    ]
