# Generated by Django 3.0.3 on 2020-12-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('posts', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
