# Generated by Django 3.0.3 on 2021-01-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
