# Generated by Django 3.0.7 on 2021-01-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='rating',
            field=models.ManyToManyField(blank=True, to='accounts.Rating'),
        ),
    ]
