# Generated by Django 3.0.3 on 2021-01-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.gif', upload_to='profile_pic'),
        ),
    ]
