# Generated by Django 3.0.3 on 2021-01-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacher_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_student',
        ),
        migrations.AddField(
            model_name='student',
            name='Role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='teacher', max_length=300, null=True),
        ),
    ]
