# Generated by Django 3.0.3 on 2021-01-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210103_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Profile_pic',
            field=models.ImageField(default='DEFAULT.jpg', upload_to='profile_pic'),
        ),
    ]
