# Generated by Django 3.0.3 on 2021-01-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Famale')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Role',
            field=models.BooleanField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
