# Generated by Django 3.0.7 on 2021-01-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacher_admin_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admin_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Nimrod'), (2, '2 - HADAS'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Perfect')], default=0),
        ),
    ]
