# Generated by Django 3.0.3 on 2021-01-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210102_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.FileField(default=False, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=300, null=True),
        ),
    ]
