# Generated by Django 3.0.3 on 2021-01-07 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_auto_20210107_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='followed_by',
            field=models.ManyToManyField(related_name='followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
