# Generated by Django 3.0.3 on 2021-01-02 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_years_in_academy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='Profile_pic',
        ),
    ]
