# Generated by Django 3.0.3 on 2021-01-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210107_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='teacher', max_length=300, null=True),
        ),
    ]
