# Generated by Django 3.0.3 on 2021-01-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210107_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Famale')], max_length=300, null=True),
        ),
    ]
