# Generated by Django 3.0.7 on 2021-01-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210108_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='source',
            new_name='text',
        ),
        migrations.AddField(
            model_name='teacher',
            name='reports',
            field=models.ManyToManyField(to='accounts.Rating'),
        ),
    ]
