# Generated by Django 3.0.7 on 2021-01-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210108_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='reports',
        ),
    ]
