# Generated by Django 3.0.7 on 2021-01-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_teacher_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Admin_Rate',
        ),
    ]
