# Generated by Django 3.0.7 on 2021-01-08 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_report_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Teacher'),
        ),
    ]
