# Generated by Django 3.1.4 on 2021-01-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210107_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Admin_Rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Under Average'), (2, '2 - Average'), (3, '3 - Great'), (4, '4 - Awesome'), (5, '4 - Master')], default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Admin_Rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Under Average'), (2, '2 - Average'), (3, '3 - Great'), (4, '4 - Awesome'), (5, '4 - Master')], default=0),
        ),
    ]
