# Generated by Django 3.0.3 on 2021-01-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='years_in_academy',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=300, null=True),
        ),
    ]
