# Generated by Django 3.0.3 on 2021-01-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210102_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='years_in_academy',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=300, null=True),
        ),
    ]
