# Generated by Django 3.0.3 on 2021-01-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210103_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_student',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
