# Generated by Django 3.0.3 on 2021-01-07 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210107_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='followed',
            field=models.ManyToManyField(related_name='followed', to='accounts.Teacher'),
        ),
        migrations.AlterField(
            model_name='following',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student'),
        ),
    ]
