# Generated by Django 3.0.3 on 2021-01-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210107_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Followed_On',
            field=models.ManyToManyField(related_name='followed', to='accounts.Teacher'),
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
