# Generated by Django 3.0.3 on 2021-01-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210107_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Followed_On',
            field=models.ManyToManyField(to='accounts.Teacher'),
        ),
    ]
