# Generated by Django 3.0.7 on 2021-01-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rating_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='student',
            new_name='user',
        ),
    ]
