# Generated by Django 3.0.7 on 2021-01-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210108_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='years_in_academy',
            field=models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate', 'Graduate')], max_length=300, null=True),
        ),
    ]
