# Generated by Django 3.0.7 on 2021-01-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210108_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='reports',
            field=models.ManyToManyField(to='accounts.File'),
        ),
    ]
